name: Daily Content Generation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    - cron: '0 12 * * *' # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-content:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'
    
    - name: Install ImageMagick
      run: |
        choco install imagemagick.app -y
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch==2.2.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
        pip install instagramapi
        
    - name: Create .env file
      run: |
        echo "IMAGEMAGICK_BINARY=magick.exe" > .env
    
    - name: Run content generation script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
        IMAGE_MAGICK_PATH: magick.exe
      run: |
        python main.py