name: Daily Content Generation
on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-content:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    
    - name: Install ImageMagick and FFmpeg
      run: |
        choco install imagemagick.app -y
        choco install ffmpeg -y
        
        
    - name: Create .env file
      run: |
        echo "IMAGEMAGICK_BINARY=C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe" > .env
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
        echo "GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}" >> .env
        echo "YOUTUBE_TOKEN=${{ secrets.YOUTUBE_TOKEN }}" >> .env
    
    - name: Run content generation script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        IMAGEMAGICK_BINARY: C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe
      run: |
        python main.py