name: Daily Content Generation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
    - cron: '0 12 * * *' # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'
    
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --upgrade pip
        
    - name: Create .env file
      run: |
        echo "IMAGEMAGICK_BINARY=/usr/bin/magick" > .env
    
    - name: Run content generation script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
        IMAGE_MAGICK_PATH: /usr/bin/magick
      run: |
        python main.py